# automatically generated by the FlatBuffers compiler, do not modify

# namespace: OrderAppProto

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class BOTTLES(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 16

    # BOTTLES
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # BOTTLES
    def Sprite(self): return self._tab.Get(flatbuffers.number_types.Int32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # BOTTLES
    def Fanta(self): return self._tab.Get(flatbuffers.number_types.Int32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))
    # BOTTLES
    def Pepsi(self): return self._tab.Get(flatbuffers.number_types.Int32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))
    # BOTTLES
    def MtnDew(self): return self._tab.Get(flatbuffers.number_types.Int32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(12))

def CreateBOTTLES(builder, sprite, fanta, pepsi, mtnDew):
    builder.Prep(4, 16)
    builder.PrependInt32(mtnDew)
    builder.PrependInt32(pepsi)
    builder.PrependInt32(fanta)
    builder.PrependInt32(sprite)
    return builder.Offset()
