# automatically generated by the FlatBuffers compiler, do not modify

# namespace: OrderAppProto

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class MILK(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = MILK()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsMILK(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # MILK
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # MILK
    def MilkType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # MILK
    def Quantity(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def Start(builder): builder.StartObject(2)
def MILKStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddMilkType(builder, milkType): builder.PrependInt8Slot(0, milkType, 0)
def MILKAddMilkType(builder, milkType):
    """This method is deprecated. Please switch to AddMilkType."""
    return AddMilkType(builder, milkType)
def AddQuantity(builder, quantity): builder.PrependFloat32Slot(1, quantity, 0.0)
def MILKAddQuantity(builder, quantity):
    """This method is deprecated. Please switch to AddQuantity."""
    return AddQuantity(builder, quantity)
def End(builder): return builder.EndObject()
def MILKEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)