# automatically generated by the FlatBuffers compiler, do not modify

# namespace: OrderAppProto

class MILK_TYPE(object):
    whole = 0
    _1 = 1
    _2 = 2
    fat_free = 3
    almond = 4
    cashew = 5
    oat = 6

