# automatically generated by the FlatBuffers compiler, do not modify

# namespace: OrderAppProto

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class DRINKS(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DRINKS()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsDRINKS(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # DRINKS
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DRINKS
    def Cans(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = o + self._tab.Pos
            from OrderAppProto.CANS import CANS
            obj = CANS()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # DRINKS
    def Bottles(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = o + self._tab.Pos
            from OrderAppProto.BOTTLES import BOTTLES
            obj = BOTTLES()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def Start(builder): builder.StartObject(2)
def DRINKSStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddCans(builder, cans): builder.PrependStructSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(cans), 0)
def DRINKSAddCans(builder, cans):
    """This method is deprecated. Please switch to AddCans."""
    return AddCans(builder, cans)
def AddBottles(builder, bottles): builder.PrependStructSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(bottles), 0)
def DRINKSAddBottles(builder, bottles):
    """This method is deprecated. Please switch to AddBottles."""
    return AddBottles(builder, bottles)
def End(builder): return builder.EndObject()
def DRINKSEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)